name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          eval "$(ssh-agent -s)"
          echo "${{ secrets.SSH_PASSPHRASE }}" | ssh-add ~/.ssh/id_rsa
          ssh-add -l
           
      - name: Deploy
        env:
          USERNAME: ${{ secrets.USERNAME }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
          APP_DIR: ${{ secrets.APP_DIR }}
        run: |
          ssh -tt -o "StrictHostKeyChecking=no" ${USERNAME}@${SERVER_IP} << EOF
            set -e
            cd ${APP_DIR}
            git pull origin main
            npm install
            npm run build
            pm2 restart my-app
            exit
          EOF
