name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy
        env:
          USERNAME: ${{ secrets.USERNAME }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
          APP_DIR: ${{ secrets.APP_DIR }}
        run: |
          ssh -o "StrictHostKeyChecking=no" ${USERNAME}@${SERVER_IP} << 'EOF'
            set -e
            cd ${APP_DIR}
            git pull origin main
            npm install
            npm run build
            pm2 restart my-app
          EOF
